In [1]:
!pip install tensorflow_probability
import tensorflow as tf
import tensorflow_probability as tfp

In [2]:
tfd = tfp.distributions

In [3]:
normal = tfd.Normal(loc=0., scale = 1.)

In [4]:
normal.sample()

<tf.Tensor: shape=(), dtype=float32, numpy=-0.28574982>

In [5]:
normal.prob(0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=0.35206532>

In [6]:
normal.log_prob(0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.0439385>

In [7]:
import numpy as np
np.log(0.352)

-1.04412410338404

In [8]:
bernoulli = tfd.Bernoulli(probs = 0.7)
bernoulli

<tfp.distributions.Bernoulli 'Bernoulli' batch_shape=[] event_shape=[] dtype=int32>

In [9]:
# the Bernoulli distribution are independent
batched_bernoulli = tfd.Bernoulli(probs = [0.4, 0.5])
batched_bernoulli.prob([0,0])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.6, 0.5], dtype=float32)>